"""Backend-neutral product layer for Linux Speech Tools."""

from .agents import ActionAdapter, AgentAdapter, AgentContractError, AgentRegistry
from .context import (
    ContextBroker,
    ContextBrokerError,
    ContextExpired,
    ContextProvider,
    ContextRegistrationError,
    RequiredContextUnavailable,
)
from .manager import ManagerStatus, SessionManager, StartResult
from .models import (
    ActionProposal,
    AgentEvent,
    AgentEventKind,
    AgentRequest,
    AgentRun,
    AgentSession,
    ApprovalGrant,
    ApprovalMethod,
    ApprovalRequest,
    Capability,
    ContextItem,
    ContextKind,
    ContextRequest,
    ContextSnapshot,
    FailureCode,
    Outcome,
    Result,
    Sensitivity,
    SessionActivity,
    SessionLifecycle,
    SessionStatus,
    TargetBinding,
    VoiceMode,
)
from .permissions import PermissionAuditEvent, PermissionBroker, PermissionDenied
from .session import VoiceSession, VoiceSessionError

__all__ = [
    "ActionAdapter",
    "ActionProposal",
    "AgentAdapter",
    "AgentContractError",
    "AgentEvent",
    "AgentEventKind",
    "AgentRequest",
    "AgentRun",
    "AgentSession",
    "AgentRegistry",
    "ApprovalGrant",
    "ApprovalMethod",
    "ApprovalRequest",
    "Capability",
    "ContextBroker",
    "ContextBrokerError",
    "ContextExpired",
    "ContextItem",
    "ContextKind",
    "ContextProvider",
    "ContextRegistrationError",
    "ContextRequest",
    "ContextSnapshot",
    "FailureCode",
    "ManagerStatus",
    "Outcome",
    "PermissionAuditEvent",
    "PermissionBroker",
    "PermissionDenied",
    "RequiredContextUnavailable",
    "Result",
    "Sensitivity",
    "SessionActivity",
    "SessionLifecycle",
    "SessionManager",
    "SessionStatus",
    "StartResult",
    "TargetBinding",
    "VoiceMode",
    "VoiceSession",
    "VoiceSessionError",
]
